name: Windows
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:          
  Windows-MinGW:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - qt_arch: mingw64_qt5-gcc
            mingw_arch: MINGW64 
            mingw_prefix: mingw-w64-x86_64
            toolchains: gcc
            c: gcc
            cxx: g++
            mkspec: win32-g++
            qt_build: qt5
          - qt_arch: mingw32_qt5-gcc
            mingw_arch: MINGW32
            mingw_prefix: mingw-w64-i686
            toolchains: gcc
            c: gcc
            cxx: g++
            mkspec: win32-g++
            qt_build: qt5
          - qt_arch: mingw64_qt5-clang
            mingw_arch: MINGW64 
            mingw_prefix: mingw-w64-x86_64
            toolchains: clang
            c: clang
            cxx: clang++
            mkspec: win32-clang-g++
            qt_build: qt5
          - qt_arch: mingw32_qt5-clang
            mingw_arch: MINGW32
            mingw_prefix: mingw-w64-i686
            toolchains: clang
            c: clang
            cxx: clang++
            mkspec: win32-clang-g++
            qt_build: qt5
          - qt_arch: mingw64_qt6-gcc
            mingw_arch: MINGW64 
            mingw_prefix: mingw-w64-x86_64
            toolchains: gcc
            c: gcc
            cxx: g++
            mkspec: win32-g++
            qt_build: qt6
          - qt_arch: mingw64_qt6-clang
            mingw_arch: MINGW64 
            mingw_prefix: mingw-w64-x86_64
            toolchains: clang
            c: clang
            cxx: clang++
            mkspec: win32-clang-g++
            qt_build: qt6
          - qt_arch: mingw32_qt6-gcc
            mingw_arch: MINGW32
            mingw_prefix: mingw-w64-i686
            toolchains: gcc
            c: gcc
            cxx: g++
            mkspec: win32-g++
            qt_build: qt6
          - qt_arch: mingw32_qt6-clang
            mingw_arch: MINGW32
            mingw_prefix: mingw-w64-i686
            toolchains: clang
            c: clang
            cxx: clang++
            mkspec: win32-clang-g++
            qt_build: qt6
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.mingw_arch }}
          install: zip make git ${{ matrix.mingw_prefix }}-${{ matrix.toolchains }} ${{ matrix.mingw_prefix }}-make ${{ matrix.mingw_prefix }}-cmake ${{ matrix.mingw_prefix }}-${{ matrix.qt_build }} ${{ matrix.mingw_prefix }}-openssl ${{ matrix.mingw_prefix }}-zstd
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true
          
      - name: Build 
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          env PATH=$PATH:/${{ matrix.mingw_arch }}/bin cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=${{ matrix.c }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -G Ninja ..
          env PATH=$PATH:/${{ matrix.mingw_arch }}/bin ninja
          mkdir bin
          cp mingwdeployqt.exe bin/
          env PATH=$PATH:/${{ matrix.mingw_arch }}/bin ./bin/mingwdeployqt.exe -d /${{ matrix.mingw_arch }}/bin bin/mingwdeployqt.exe
          cd ..

      - name: upload executable artifact
        uses: actions/upload-artifact@v1
        with:
          path: build\bin
          name: mingwdeployqt-${{ matrix.qt_arch }}
